spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_prod
    username: "gym"
    password: "gym"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migrations"
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always