version: "3.8"
services:
  postgres-stud:
    image: postgres:16.0
    restart: on-failure
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
    ports:
      - "5432:5432"
    volumes:
      - postgres-stud-db-data:/var/lib/postgresql/data
    networks:
      - stud-network
  tomcat-stud:
    image: tomcat:10.0-jdk17-corretto
    depends_on:
      - postgres-stud
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    networks:
      - stud-network

volumes:
  postgres-stud-db-data:

networks:
  stud-network:



