version: "3.8"
services:
  postgres-stud:
    image: postgres:16.0
    restart: on-failure
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
    ports:
      - "5432:5432"
    volumes:
      - postgres-stud-db-data:/var/lib/postgresql/data
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./webapps/Spring-core-task-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/Spring-core-task-1.0-SNAPSHOT.war

volumes:
  postgres-stud-db-data:

