version: "3.8"
services:
  postgres-stud:
    image: postgres:16.0
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres-stud-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: gym
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - stud-network

volumes:
  postgres-stud-db-data:

networks:
  stud-network:



