version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gym
    ports:
      - "5432:5432"
