CREATE USER gym WITH ENCRYPTED PASSWORD 'gym';

CREATE DATABASE gym;
GRANT ALL ON DATABASE gym to gym;
ALTER DATABASE gym OWNER TO gym;

CREATE DATABASE gym_local;
GRANT ALL ON DATABASE gym_local to gym;
ALTER DATABASE gym_local OWNER TO gym;

CREATE DATABASE gym_prod;
GRANT ALL ON DATABASE gym_prod to gym;
ALTER DATABASE gym_prod OWNER TO gym;

CREATE DATABASE gym_test;
GRANT ALL ON DATABASE gym_test to gym;
ALTER DATABASE gym_test OWNER TO gym;
